Rework package build process

diff --git a/tuxedo-drivers.spec.in b/tuxedo-drivers.spec.in
--- a/tuxedo-drivers.spec.in
+++ b/tuxedo-drivers.spec.in
@@ -1,33 +1,17 @@
-%define module module-name
-
-#
-# spec file for package tuxedo-drivers
-#
-# Copyright (c) 2019 SUSE LINUX GmbH, Nuernberg, Germany.
-#
-# All modifications and additions to the file contributed by third parties
-# remain the property of their copyright owners, unless otherwise agreed
-# upon. The license for this file, and modifications and additions to the
-# file, is the same license as for the pristine package itself (unless the
-# license for the pristine package is not an Open Source License, in which
-# case the license is the MIT License). An "Open Source License" is a
-# license that conforms to the Open Source Definition (Version 1.9)
-# published by the Open Source Initiative.
-
-# Please submit bugfixes or comments via http://bugs.opensuse.org/
-#
-
-
+Name:           tuxedo-drivers
+Version:        #MODULE_VERSION#
+Release:        1%{?dist}
 Summary:        Kernel modules for TUXEDO devices
-Name:           %{module}
-Version:        x.x.x
-Release:        x
+
 License:        GPLv3+
-Group:          Hardware/Other
-BuildArch:      noarch
 Url:            https://www.tuxedocomputers.com
-Source:         %{module}-%{version}.tar.bz2
-Provides:       tuxedo-keyboard = %{version}-%{release}
+Source0:        %{name}-%{version}.tar.xz
+
+Requires:       dkms >= 2.1
+
+BuildArch:      noarch
+
+Provides:       tuxedo-keyboard = 4.0.0-1
 Obsoletes:      tuxedo-cc-wmi
 Obsoletes:      tuxedo-keyboard < 4.0.0~
 Obsoletes:      tuxedo_keyboard
@@ -37,8 +21,8 @@ Obsoletes:      tuxedo-touchpad-fix
 Obsoletes:      tuxedo-wmi-dkms
 Obsoletes:      tuxedo-xp-xc-airplane-mode-fix
 Obsoletes:      tuxedo-xp-xc-touchpad-key-fix
-Requires:       dkms >= 1.95
-BuildRoot:      %{_tmppath}
+
+Group:          Hardware/Other
 Packager:       TUXEDO Computers GmbH <tux@tuxedocomputers.com>
 
 %description
@@ -46,128 +30,83 @@ Drivers for several platform devices for TUXEDO notebooks meant for DKMS
 framework.
 
 %prep
-%setup -n %{module}-%{version} -q
+%setup
 
 %install
-rm -rf %{buildroot}
-mkdir -p %{buildroot}/usr/src/%{module}-%{version}/
-cp dkms.conf Makefile %{buildroot}/usr/src/%{module}-%{version}
-cp -R src/ %{buildroot}/usr/src/%{module}-%{version}
-mkdir -p %{buildroot}/usr/share/
-mkdir -p %{buildroot}/usr/share/%{module}/
-cp postinst %{buildroot}/usr/share/%{module}
-cp tuxedo_keyboard.conf %{buildroot}/usr/share/%{module}
-
-%clean
-rm -rf %{buildroot}
+cp -r %{_builddir}/%{name}-%{version}/usr %{buildroot}
+cp -r %{_builddir}/%{name}-%{version}/etc %{buildroot}
 
 %files
-%defattr(0644,root,root,0755)
-%attr(0755,root,root) /usr/src/%{module}-%{version}/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/*
-%attr(0755,root,root) /usr/src/%{module}-%{version}/src/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/src/*
-%attr(0755,root,root) /usr/src/%{module}-%{version}/src/tuxedo_io/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/src/tuxedo_io/*
-%attr(0755,root,root) /usr/src/%{module}-%{version}/src/ite_8291/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/src/ite_8291/*
-%attr(0755,root,root) /usr/src/%{module}-%{version}/src/ite_8291_lb/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/src/ite_8291_lb/*
-%attr(0755,root,root) /usr/src/%{module}-%{version}/src/ite_8297/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/src/ite_8297/*
-%attr(0755,root,root) /usr/src/%{module}-%{version}/src/ite_829x/
-%attr(0644,root,root) /usr/src/%{module}-%{version}/src/ite_829x/*
-%attr(0755,root,root) /usr/share/%{module}/
-%attr(0755,root,root) /usr/share/%{module}/postinst
-%attr(0644,root,root) /usr/share/%{module}/tuxedo_keyboard.conf
+%{_usr}
+%{_sysconfdir}
+%dir %{_usrsrc}/%{name}-%{version}
 %license LICENSE
 
 %post
-for POSTINST in /usr/lib/dkms/common.postinst /usr/share/%{module}/postinst; do
-    if [ -f $POSTINST ]; then
-        $POSTINST %{module} %{version} /usr/share/%{module}
-        RET=$?
-
-        # Attempt to (re-)load module immediately, fail silently if not possible at this stage
-
-        # Also stop tccd service if running before
-        echo "Check tccd running status"
-        if systemctl is-active --quiet tccd.service; then
-            TCCD_RUNNING=true
-        else
-            TCCD_RUNNING=false
-        fi
-
-        if $TCCD_RUNNING; then
-            echo "Stop tccd temporarily"
-            systemctl stop tccd 2>&1 || true
-        fi
-
-        % Explicitly unload old tuxedo_cc_wmi if loaded at this point
-        rmmod tuxedo_cc_wmi > /dev/null 2>&1 || true
-
-        echo "(Re)load modules if possible"
-
-        rmmod tuxedo_io > /dev/null 2>&1 || true
-        rmmod uniwill_wmi > /dev/null 2>&1 || true
-        rmmod clevo_wmi > /dev/null 2>&1 || true
-        rmmod clevo_acpi > /dev/null 2>&1 || true
-        rmmod tuxedo_keyboard > /dev/null 2>&1 || true
-        
-        modprobe tuxedo_keyboard > /dev/null 2>&1 || true
-        modprobe uniwill_wmi > /dev/null 2>&1 || true
-        modprobe clevo_wmi > /dev/null 2>&1 || true
-        modprobe clevo_acpi > /dev/null 2>&1 || true
-        modprobe tuxedo_io > /dev/null 2>&1 || true
-
-        rmmod ite_829x > /dev/null 2>&1 || true
-        modprobe ite_829x > /dev/null 2>&1 || true
-        rmmod ite_8297 > /dev/null 2>&1 || true
-        modprobe ite_8297 > /dev/null 2>&1 || true
-        rmmod ite_8291 > /dev/null 2>&1 || true
-        modprobe ite_8291 > /dev/null 2>&1 || true
-        rmmod ite_8291_lb > /dev/null 2>&1 || true
-        modprobe ite_8291_lb > /dev/null 2>&1 || true
-
-        # Install default config if none exist already
-        if [ ! -f "/etc/modprobe.d/tuxedo_keyboard.conf" ]; then
-            cp -f /usr/share/tuxedo-drivers/tuxedo_keyboard.conf /etc/modprobe.d/tuxedo_keyboard.conf
-        fi
-
-        # Restart tccd after reload if it was running
-        if $TCCD_RUNNING; then
-            echo "Start tccd again"
-            systemctl start tccd 2>&1 || true
-        fi
-
-        exit $RET
-    fi
-    echo "WARNING: $POSTINST does not exist."
-done
-
-echo -e "ERROR: DKMS version is too old and %{module} was not"
-echo -e "built with legacy DKMS support."
-echo -e "You must either rebuild %{module} with legacy postinst"
-echo -e "support or upgrade DKMS to a more current version."
-exit 1
-
+# Install modules via DKMS
+dkms add -m %{name} -v %{version} --rpm_safe_upgrade
+dkms build -m %{name} -v %{version}
+dkms install -m %{name} -v %{version}
+# Attempt to (re-)load modules and tccd, fail silently if not possible
+# Stop tccd service if it was running before
+echo "Check tccd running status"
+if systemctl is-active --quiet tccd.service; then
+    TCCD_RUNNING=true
+    echo "Stop tccd temporarily"
+    systemctl stop tccd 2>&1 || true
+fi
+# (Re-)load modules
+echo "(Re)load modules if possible"
+rmmod tuxedo_io > /dev/null 2>&1 || true
+rmmod uniwill_wmi > /dev/null 2>&1 || true
+rmmod clevo_wmi > /dev/null 2>&1 || true
+rmmod clevo_acpi > /dev/null 2>&1 || true
+rmmod tuxedo_keyboard > /dev/null 2>&1 || true
+modprobe tuxedo_keyboard > /dev/null 2>&1 || true
+modprobe clevo_acpi > /dev/null 2>&1 || true
+modprobe clevo_wmi > /dev/null 2>&1 || true
+modprobe uniwill_wmi > /dev/null 2>&1 || true
+modprobe tuxedo_io > /dev/null 2>&1 || true
+rmmod ite_8291 > /dev/null 2>&1 || true
+modprobe ite_8291 > /dev/null 2>&1 || true
+rmmod ite_8291_lb > /dev/null 2>&1 || true
+modprobe ite_8291_lb > /dev/null 2>&1 || true
+rmmod ite_8297 > /dev/null 2>&1 || true
+modprobe ite_8297 > /dev/null 2>&1 || true
+rmmod ite_829x > /dev/null 2>&1 || true
+modprobe ite_829x > /dev/null 2>&1 || true
+# Restart tccd after reload if it was running before
+if $TCCD_RUNNING; then
+	echo "Start tccd again"
+	systemctl start tccd 2>&1 || true
+fi
 
 %preun
-echo -e
-echo -e "Uninstall of %{module} module (version %{version}-%{release}) beginning:"
-dkms remove -m %{module} -v %{version} --all --rpm_safe_upgrade
-if [ $1 != 1 ];then
-    /usr/sbin/rmmod %{module} > /dev/null 2>&1 || true
-    rm -f /etc/modprobe.d/tuxedo_keyboard.conf || true
-    /usr/sbin/rmmod ite_829x > /dev/null 2>&1 || true
-    /usr/sbin/rmmod ite_8297 > /dev/null 2>&1 || true
-    /usr/sbin/rmmod ite_8291 > /dev/null 2>&1 || true
-    /usr/sbin/rmmod ite_8291_lb > /dev/null 2>&1 || true
-fi
-exit 0
-
+# Attempt to unload modules, fail silently if not possible
+echo "Unload modules if possible"
+rmmod tuxedo_io > /dev/null 2>&1 || true
+rmmod uniwill_wmi > /dev/null 2>&1 || true
+rmmod clevo_wmi > /dev/null 2>&1 || true
+rmmod clevo_acpi > /dev/null 2>&1 || true
+rmmod tuxedo_keyboard > /dev/null 2>&1 || true
+rmmod ite_8291 > /dev/null 2>&1 || true
+rmmod ite_8291_lb > /dev/null 2>&1 || true
+rmmod ite_8297 > /dev/null 2>&1 || true
+rmmod ite_829x > /dev/null 2>&1 || true
+# Remove modules via DKMS
+dkms remove -m %{name} -v %{version} --all --rpm_safe_upgrade
 
 %changelog
+* Mon Nov 20 2023 C Sandberg <tux@tuxedocomputers.com> 4.0.0-1
+- Merge tuxedo-keyboard and tuxedo-keyboard-ite
+- Rename package
+- Rework packaging process
+* Thu Nov 16 2023 C Sandberg <tux@tuxedocomputers.com> 3.2.14-1
+- Tweak IBPG8 tdp limits
+* Fri Nov 10 2023 C Sandberg <tux@tuxedocomputers.com> 3.2.13-1
+- Add missing IBPG8 TDP definitions
+* Tue Oct 24 2023 C Sandberg <tux@tuxedocomputers.com> 3.2.12-1
+- Polaris/Stellaris AMD Gen5 support
 * Thu Sep 21 2023 C Sandberg <tux@tuxedocomputers.com> 3.2.11-1
 - Aura Gen3 support
 * Thu Aug 10 2023 C Sandberg <tux@tuxedocomputers.com> 3.2.10-1
@@ -291,3 +230,40 @@ exit 0
 - New packaging
 * Wed Dec 18 2019 Richard Sailer <tux@tuxedocomputers.com> 2.0.0-1
 - Initial DKMS package for back-lit keyboard 2nd generation
+* Thu Nov 16 2023 C Sandberg <tux@tuxedocomputers.com> 0.4.4-1
+- Add color scaling for Stellaris Gen5 AMD devices
+* Thu Aug 03 2023 C Sandberg <tux@tuxedocomputers.com> 0.4.3-1
+- Adjusted lightbar USB product exclusion (prevents driver binding to unused
+  devices) for Stellaris Gen5 and allows proper binding of relevant ones.
+- Lightbar color scaling for Stellaris 17 Gen5
+* Thu May 04 2023 C Sandberg <tux@tuxedocomputers.com> 0.4.1-1
+- Four zone backlight support for Stellaris Gen5
+- Experimental buffered writes for Stellaris/Fusion per-key variants
+* Mon Apr 17 2023 C Sandberg <tux@tuxedocomputers.com> 0.4.0-1
+- Color scaling for Stellaris Intel Gen5
+- Lightbar impl. for Stellaris Gen4/5
+* Thu Feb 23 2023 C Sandberg <tux@tuxedocomputers.com> 0.3.0-1
+- Leds interface support (/sys/class/leds)
+* Wed Dec 07 2022 C Sandberg <tux@tuxedocomputers.com> 0.2.5-1
+- Add per-device color scaling to ite_8291 driver
+- Add additional scaling setting for Stellaris 17 AMD Gen 4
+* Wed Nov 30 2022 C Sandberg <tux@tuxedocomputers.com> 0.2.4-1
+- Add USB ID for Stellaris 17 Gen 4 keyboard backlight
+* Mon Feb 22 2021 C Sandberg <tux@tuxedocomputers.com> 0.2.3-1
+- Fix broken brightness key reaction for ite_829x
+* Tue Feb 16 2021 C Sandberg <tux@tuxedocomputers.com> 0.2.2-1
+- Attempt to fix ite_829x instability sometimes locking up kernel on keypress
+* Mon Dec 21 2020 C Sandberg <tux@tuxedocomputers.com> 0.2.1-1
+- Added device 048d:6004 to ite_8291
+* Fri Nov 13 2020 C Sandberg <tux@tuxedocomputers.com> 0.2.0-1
+- Added initial support for ITE Device(8291) ->  048d:ce00
+* Fri Oct 16 2020 C Sandberg <tux@tuxedocomputers.com> 0.1.0-1
+- Added initial (very basic) support for 048d:8297 LED controller
+* Mon Oct 12 2020 C Sandberg <tux@tuxedocomputers.com> 0.0.3-1
+- Fixed key mapping toggle <=> switch mode
+- Default color to white
+* Tue Sep 29 2020 C Sandberg <tux@tuxedocomputers.com> 0.0.2-1
+- Initial experimental release
+* Thu Apr 23 2020 C Sandberg <tux@tuxedocomputers.com> 0.0.1-1
+- First version of the ITE keyboard backlight driver
+- Has support for ITE Device(829x) ->  0x048d:0x8910
